/**
 * Static map of custom task category image assets.
 * Metro bundler requires static require paths.
 */
export const TASK_ICON_ASSETS: Record<string, any> = {
  mosque: require('../../assets/icons/task_icons/mosque.png'),
  'quran': require('../../assets/icons/task_icons/quran.png'),
  'kaaba': require('../../assets/icons/task_icons/kaaba.png'),
  'crescent': require('../../assets/icons/task_icons/crescent.png'),
  'beads': require('../../assets/icons/task_icons/beads.png'),
  'charity': require('../../assets/icons/task_icons/charity.png'),
  'duaa': require('../../assets/icons/task_icons/duaa.png'),
  'fasting': require('../../assets/icons/task_icons/fasting.png'),
  'lectures': require('../../assets/icons/task_icons/lectures.png'),
  'water-wudu': require('../../assets/icons/task_icons/water-wudu.png'),
  'heart-deen': require('../../assets/icons/task_icons/heart-deen.png'),
  'star-islamic': require('../../assets/icons/task_icons/star-islamic.png'),
  'compass-qibla': require('../../assets/icons/task_icons/compass-qibla.png'),
  'sujood': require('../../assets/icons/task_icons/sujood.png'),
  'dua-praise': require('../../assets/icons/task_icons/dua-praise.png'),
  'sun': require('../../assets/icons/task_icons/sun.png'),
  'moon-sleep': require('../../assets/icons/task_icons/moon-sleep.png'),
  'coffee': require('../../assets/icons/task_icons/coffee.png'),
  'tea': require('../../assets/icons/task_icons/tea.png'),
  'breakfast': require('../../assets/icons/task_icons/breakfast.png'),
  'shower': require('../../assets/icons/task_icons/shower.png'),
  'water-hydration': require('../../assets/icons/task_icons/water-hydration.png'),
  'walk': require('../../assets/icons/task_icons/walk.png'),
  'journal': require('../../assets/icons/task_icons/journal.png'),
  'alarm': require('../../assets/icons/task_icons/alarm.png'),
  'laptop': require('../../assets/icons/task_icons/laptop.png'),
  'book': require('../../assets/icons/task_icons/book.png'),
  'graduation': require('../../assets/icons/task_icons/graduation.png'),
  'briefcase': require('../../assets/icons/task_icons/briefcase.png'),
  'pencil': require('../../assets/icons/task_icons/pencil.png'),
  'document': require('../../assets/icons/task_icons/document.png'),
  'presentation': require('../../assets/icons/task_icons/presentation.png'),
  'code': require('../../assets/icons/task_icons/code.png'),
  'calculator': require('../../assets/icons/task_icons/calculator.png'),
  'email': require('../../assets/icons/task_icons/email.png'),
  'dumbbell': require('../../assets/icons/task_icons/dumbbell.png'),
  'running': require('../../assets/icons/task_icons/running.png'),
  'cycling': require('../../assets/icons/task_icons/cycling.png'),
  'yoga': require('../../assets/icons/task_icons/yoga.png'),
  'pill': require('../../assets/icons/task_icons/pill.png'),
  'doctor': require('../../assets/icons/task_icons/doctor.png'),
  'dentist': require('../../assets/icons/task_icons/dentist.png'),
  'nutrition': require('../../assets/icons/task_icons/nutrition.png'),
  'pulse': require('../../assets/icons/task_icons/pulse.png'),
  'home': require('../../assets/icons/task_icons/home.png'),
  'groceries': require('../../assets/icons/task_icons/groceries.png'),
  'cooking': require('../../assets/icons/task_icons/cooking.png'),
  'cleaning': require('../../assets/icons/task_icons/cleaning.png'),
  'laundry': require('../../assets/icons/task_icons/laundry.png'),
  'car': require('../../assets/icons/task_icons/car.png'),
  'trash': require('../../assets/icons/task_icons/trash.png'),
  'repair': require('../../assets/icons/task_icons/repair.png'),
  'plant': require('../../assets/icons/task_icons/plant.png'),
  'package': require('../../assets/icons/task_icons/package.png'),
  'family': require('../../assets/icons/task_icons/family.png'),
  'baby': require('../../assets/icons/task_icons/baby.png'),
  'call': require('../../assets/icons/task_icons/call.png'),
  'chat': require('../../assets/icons/task_icons/chat.png'),
  'gift': require('../../assets/icons/task_icons/gift.png'),
  'party': require('../../assets/icons/task_icons/party.png'),
  'pet': require('../../assets/icons/task_icons/pet.png'),
  'palette': require('../../assets/icons/task_icons/palette.png'),
  'camera': require('../../assets/icons/task_icons/camera.png'),
  'headphones': require('../../assets/icons/task_icons/headphones.png'),
  'airplane': require('../../assets/icons/task_icons/airplane.png'),
  'gaming': require('../../assets/icons/task_icons/gaming.png'),
  'shopping-bag': require('../../assets/icons/task_icons/shopping-bag.png'),
  'target': require('../../assets/icons/task_icons/target.png'),
  'bulb': require('../../assets/icons/task_icons/bulb.png'),
  'fire': require('../../assets/icons/task_icons/fire.png'),
  'trophy': require('../../assets/icons/task_icons/trophy.png'),
  'flag': require('../../assets/icons/task_icons/flag.png'),
  'pin': require('../../assets/icons/task_icons/pin.png'),
  'clock': require('../../assets/icons/task_icons/clock.png'),
  'checkmark': require('../../assets/icons/task_icons/checkmark.png'),
  // ─── 🕌 Deen & Worship Expansion ───
  'prayer-mat': require('../../assets/icons/task_icons/prayer-mat.png'),
  'tahajjud': require('../../assets/icons/task_icons/tahajjud.png'),
  'hajj': require('../../assets/icons/task_icons/hajj.png'),
  'quran-memorization': require('../../assets/icons/task_icons/quran-memorization.png'),
  'zakat': require('../../assets/icons/task_icons/zakat.png'),
  'dates-fruit': require('../../assets/icons/task_icons/dates-fruit.png'),
  'janazah': require('../../assets/icons/task_icons/janazah.png'),
  'miswak': require('../../assets/icons/task_icons/miswak.png'),
  // ─── ☀️ Routine & Daily Life Expansion ───
  'bed-nap': require('../../assets/icons/task_icons/bed-nap.png'),
  'toothbrush': require('../../assets/icons/task_icons/toothbrush.png'),
  'skincare': require('../../assets/icons/task_icons/skincare.png'),
  'bath': require('../../assets/icons/task_icons/bath.png'),
  'water-jug': require('../../assets/icons/task_icons/water-jug.png'),
  // ─── 💼 Work & Study Expansion ───
  'desk': require('../../assets/icons/task_icons/desk.png'),
  'meeting': require('../../assets/icons/task_icons/meeting.png'),
  'certificate': require('../../assets/icons/task_icons/certificate.png'),
  'folder': require('../../assets/icons/task_icons/folder.png'),
  'microscope': require('../../assets/icons/task_icons/microscope.png'),
  // ─── 💰 Finance & Money ───
  'wallet': require('../../assets/icons/task_icons/wallet.png'),
  'money': require('../../assets/icons/task_icons/money.png'),
  'credit-card': require('../../assets/icons/task_icons/credit-card.png'),
  'piggy-bank': require('../../assets/icons/task_icons/piggy-bank.png'),
  'invoice': require('../../assets/icons/task_icons/invoice.png'),
  // ─── ✈️ Travel & Commute ───
  'luggage': require('../../assets/icons/task_icons/luggage.png'),
  'bus': require('../../assets/icons/task_icons/bus.png'),
  'train': require('../../assets/icons/task_icons/train.png'),
  'passport': require('../../assets/icons/task_icons/passport.png'),
  'gas-station': require('../../assets/icons/task_icons/gas-station.png'),
  // ─── 🏃 Health & Fitness Expansion ───
  'swimming': require('../../assets/icons/task_icons/swimming.png'),
  'hiking': require('../../assets/icons/task_icons/hiking.png'),
  'apple': require('../../assets/icons/task_icons/apple.png'),
  'scale': require('../../assets/icons/task_icons/scale.png'),
  'sleep-mask': require('../../assets/icons/task_icons/sleep-mask.png'),
  // ─── 🏠 Home & Chores Expansion ───
  'bed-making': require('../../assets/icons/task_icons/bed-making.png'),
  'dishes': require('../../assets/icons/task_icons/dishes.png'),
  'grocery-cart': require('../../assets/icons/task_icons/grocery-cart.png'),
  'lightbulb-fixture': require('../../assets/icons/task_icons/lightbulb-fixture.png'),
  'key': require('../../assets/icons/task_icons/key.png'),
  // ─── 👥 Family & Social Expansion ───
  'handshake': require('../../assets/icons/task_icons/handshake.png'),
  'dinner-table': require('../../assets/icons/task_icons/dinner-table.png'),
  'crying-baby': require('../../assets/icons/task_icons/crying-baby.png'),
  'elderly': require('../../assets/icons/task_icons/elderly.png'),
  // ─── 🎨 Leisure & Hobbies Expansion ───
  'gardening-trowel': require('../../assets/icons/task_icons/gardening-trowel.png'),
  'book-shelf': require('../../assets/icons/task_icons/book-shelf.png'),
  'guitar': require('../../assets/icons/task_icons/guitar.png'),
  'board-game': require('../../assets/icons/task_icons/board-game.png'),
  // ─── ⭐ Productivity & Goals Expansion ───
  'rocket': require('../../assets/icons/task_icons/rocket.png'),
  'timer': require('../../assets/icons/task_icons/timer.png'),
  'shield': require('../../assets/icons/task_icons/shield.png'),
  'calendar': require('../../assets/icons/task_icons/calendar.png'),
  // ─── 🌟 Lifestyle, Grooming & Errands Expansion ───
  'haircut': require('../../assets/icons/task_icons/haircut.png'),
  'clothing': require('../../assets/icons/task_icons/clothing.png'),
  'stroller': require('../../assets/icons/task_icons/stroller.png'),
  'car-wash': require('../../assets/icons/task_icons/car-wash.png'),
  'restaurant': require('../../assets/icons/task_icons/restaurant.png'),
  'fast-food': require('../../assets/icons/task_icons/fast-food.png'),
  // ─── ⚽ Sports & Recreation ───
  'soccer': require('../../assets/icons/task_icons/soccer.png'),
  'basketball': require('../../assets/icons/task_icons/basketball.png'),
  'tennis': require('../../assets/icons/task_icons/tennis.png'),
  'archery': require('../../assets/icons/task_icons/archery.png'),
  // ─── 🏖️ Travel, Outdoors & Nature ───
  'beach': require('../../assets/icons/task_icons/beach.png'),
  'camping': require('../../assets/icons/task_icons/camping.png'),
  'hotel': require('../../assets/icons/task_icons/hotel.png'),
  'shifa-honey': require('../../assets/icons/task_icons/shifa-honey.png'),
  // ─── 📚 School, Learning & Exams ───
  'exam': require('../../assets/icons/task_icons/exam.png'),
  'backpack': require('../../assets/icons/task_icons/backpack.png'),
  'language': require('../../assets/icons/task_icons/language.png'),
  // ─── 🔔 To-Do Utility Symbols & Flags ───
  'bell': require('../../assets/icons/task_icons/bell.png'),
  'sparkles': require('../../assets/icons/task_icons/sparkles.png'),
  'lightning': require('../../assets/icons/task_icons/lightning.png'),
  'battery': require('../../assets/icons/task_icons/battery.png'),
  'bookmark': require('../../assets/icons/task_icons/bookmark.png'),
  'hourglass': require('../../assets/icons/task_icons/hourglass.png'),
  'flag-checkered': require('../../assets/icons/task_icons/flag-checkered.png'),
};

/**
 * Helper to check if an icon ID has a custom image asset
 */
export function hasCustomTaskIcon(iconId?: string | null): boolean {
  if (!iconId) return false;
  return Boolean(TASK_ICON_ASSETS[iconId]);
}
