/**
 * Static map of custom task category image assets.
 * Metro bundler requires static require paths.
 */
export const TASK_ICON_ASSETS: Record<string, any> = {
  mosque: require('../../assets/icons/task_icons/mosque.png'),
  'quran': require('../../assets/icons/task_icons/quran.png'),
  'kaaba': require('../../assets/icons/task_icons/kaaba.png'),
  'crescent': require('../../assets/icons/task_icons/crescent.png'),
  'beads': require('../../assets/icons/task_icons/beads.png'),
  'charity': require('../../assets/icons/task_icons/charity.png'),
  'duaa': require('../../assets/icons/task_icons/duaa.png'),
  'fasting': require('../../assets/icons/task_icons/fasting.png'),
  'lectures': require('../../assets/icons/task_icons/lectures.png'),
  'water-wudu': require('../../assets/icons/task_icons/water-wudu.png'),
  'heart-deen': require('../../assets/icons/task_icons/heart-deen.png'),
  'star-islamic': require('../../assets/icons/task_icons/star-islamic.png'),
  'compass-qibla': require('../../assets/icons/task_icons/compass-qibla.png'),
  'sujood': require('../../assets/icons/task_icons/sujood.png'),
  'dua-praise': require('../../assets/icons/task_icons/dua-praise.png'),
  'sun': require('../../assets/icons/task_icons/sun.png'),
  'moon-sleep': require('../../assets/icons/task_icons/moon-sleep.png'),
  'coffee': require('../../assets/icons/task_icons/coffee.png'),
  'tea': require('../../assets/icons/task_icons/tea.png'),
  'breakfast': require('../../assets/icons/task_icons/breakfast.png'),
  'shower': require('../../assets/icons/task_icons/shower.png'),
  'water-hydration': require('../../assets/icons/task_icons/water-hydration.png'),
  'walk': require('../../assets/icons/task_icons/walk.png'),
  'journal': require('../../assets/icons/task_icons/journal.png'),
  'alarm': require('../../assets/icons/task_icons/alarm.png'),
  'laptop': require('../../assets/icons/task_icons/laptop.png'),
  'book': require('../../assets/icons/task_icons/book.png'),
  'graduation': require('../../assets/icons/task_icons/graduation.png'),
  'briefcase': require('../../assets/icons/task_icons/briefcase.png'),
  'pencil': require('../../assets/icons/task_icons/pencil.png'),
  'document': require('../../assets/icons/task_icons/document.png'),
  'presentation': require('../../assets/icons/task_icons/presentation.png'),
  'code': require('../../assets/icons/task_icons/code.png'),
  'calculator': require('../../assets/icons/task_icons/calculator.png'),
  'email': require('../../assets/icons/task_icons/email.png'),
  'dumbbell': require('../../assets/icons/task_icons/dumbbell.png'),
  'running': require('../../assets/icons/task_icons/running.png'),
  'cycling': require('../../assets/icons/task_icons/cycling.png'),
  'yoga': require('../../assets/icons/task_icons/yoga.png'),
  'pill': require('../../assets/icons/task_icons/pill.png'),
  'doctor': require('../../assets/icons/task_icons/doctor.png'),
  'dentist': require('../../assets/icons/task_icons/dentist.png'),
  'nutrition': require('../../assets/icons/task_icons/nutrition.png'),
  'pulse': require('../../assets/icons/task_icons/pulse.png'),
  'home': require('../../assets/icons/task_icons/home.png'),
  'groceries': require('../../assets/icons/task_icons/groceries.png'),
  'cooking': require('../../assets/icons/task_icons/cooking.png'),
  'cleaning': require('../../assets/icons/task_icons/cleaning.png'),
  'laundry': require('../../assets/icons/task_icons/laundry.png'),
  'car': require('../../assets/icons/task_icons/car.png'),
  'trash': require('../../assets/icons/task_icons/trash.png'),
  'repair': require('../../assets/icons/task_icons/repair.png'),
  'plant': require('../../assets/icons/task_icons/plant.png'),
  'package': require('../../assets/icons/task_icons/package.png'),
  'family': require('../../assets/icons/task_icons/family.png'),
  'baby': require('../../assets/icons/task_icons/baby.png'),
  'call': require('../../assets/icons/task_icons/call.png'),
  'chat': require('../../assets/icons/task_icons/chat.png'),
  'gift': require('../../assets/icons/task_icons/gift.png'),
  'party': require('../../assets/icons/task_icons/party.png'),
  'pet': require('../../assets/icons/task_icons/pet.png'),
  'palette': require('../../assets/icons/task_icons/palette.png'),
  'camera': require('../../assets/icons/task_icons/camera.png'),
  'headphones': require('../../assets/icons/task_icons/headphones.png'),
  'airplane': require('../../assets/icons/task_icons/airplane.png'),
  'gaming': require('../../assets/icons/task_icons/gaming.png'),
  'shopping-bag': require('../../assets/icons/task_icons/shopping-bag.png'),
  'target': require('../../assets/icons/task_icons/target.png'),
  'bulb': require('../../assets/icons/task_icons/bulb.png'),
  'fire': require('../../assets/icons/task_icons/fire.png'),
  'trophy': require('../../assets/icons/task_icons/trophy.png'),
  'flag': require('../../assets/icons/task_icons/flag.png'),
  'pin': require('../../assets/icons/task_icons/pin.png'),
  'clock': require('../../assets/icons/task_icons/clock.png'),
  'checkmark': require('../../assets/icons/task_icons/checkmark.png'),
};

/**
 * Helper to check if an icon ID has a custom image asset
 */
export function hasCustomTaskIcon(iconId?: string | null): boolean {
  if (!iconId) return false;
  return Boolean(TASK_ICON_ASSETS[iconId]);
}
