import type { ImageSourcePropType } from 'react-native';
import type { ThemeColors } from './tokens';

export interface IslamicThemeDefinition {
  id: string;
  name: string;
  arabicName: string;
  tagline: string;
  isDark: boolean;
  wallpaperAsset?: ImageSourcePropType;
  previewColors: {
    primary: string;
    background: string;
    surface: string;
    accent: string;
  };
  colors: ThemeColors;
}

export const fajrAwakeningColors: ThemeColors = {
  primary: '#F59E0B',
  primaryLight: '#2D2338',
  primaryDark: '#D97706',
  primaryPressed: '#B45309',
  background: '#161A36',
  surface: 'rgba(30, 36, 75, 0.75)',
  surfaceSecondary: 'rgba(37, 44, 88, 0.65)',
  surfaceElevated: 'rgba(45, 53, 104, 0.85)',
  textPrimary: '#FDFCFB',
  textSecondary: '#A5A0B8',
  textTertiary: '#857F9A',
  textMuted: '#65607A',
  textOnPrimary: '#161A36',
  success: '#10B981',
  warning: '#F59E0B',
  danger: '#EF4444',
  error: '#EF4444',
  dangerPressed: '#DC2626',
  dangerSurface: '#381E28',
  info: '#38BDF8',
  completed: '#10B981',
  prayerFajr: '#2B2B5C',
  prayerDhuhr: '#2E2848',
  prayerAsr: '#342540',
  prayerMaghrib: '#381F38',
  prayerIsha: '#1E2248',
  border: '#2C3464',
  divider: '#222952',
  shadowColor: 'rgba(0, 0, 0, 0.4)',
  shadowElevated: 'rgba(0, 0, 0, 0.6)',
  overlay: 'rgba(10, 12, 28, 0.75)',
  tabInactive: '#857F9A',
  tabActive: '#F59E0B',
  checkboxUnchecked: '#434D7E',
  checkboxChecked: '#F59E0B',
  disabledBackground: '#262E58',
  disabledText: '#65607A',
};

export const rawdahEmeraldColors: ThemeColors = {
  primary: '#0F8A52',
  primaryLight: '#EBF5EF',
  primaryDark: '#0B6A3E',
  primaryPressed: '#0B6A3E',
  background: '#F9F7F2',
  surface: 'rgba(255, 255, 255, 0.88)',
  surfaceSecondary: 'rgba(242, 239, 232, 0.80)',
  surfaceElevated: 'rgba(255, 255, 255, 0.96)',
  textPrimary: '#152C20',
  textSecondary: '#5A7064',
  textTertiary: '#6E8578',
  textMuted: '#8E99A8',
  textOnPrimary: '#FFFFFF',
  success: '#0F8A52',
  warning: '#D4A017',
  danger: '#C0392B',
  error: '#C0392B',
  dangerPressed: '#962D22',
  dangerSurface: '#FEE7E7',
  info: '#0284C7',
  completed: '#0F8A52',
  prayerFajr: '#EDEBF5',
  prayerDhuhr: '#FFF6E5',
  prayerAsr: '#FFF0DB',
  prayerMaghrib: '#FFE6E6',
  prayerIsha: '#E8ECF5',
  border: '#E2DDD4',
  divider: '#EDE9E1',
  shadowColor: 'rgba(21, 44, 32, 0.08)',
  shadowElevated: 'rgba(21, 44, 32, 0.15)',
  overlay: 'rgba(0, 0, 0, 0.45)',
  tabInactive: '#6E8578',
  tabActive: '#0F8A52',
  checkboxUnchecked: '#C5CFC9',
  checkboxChecked: '#0F8A52',
  disabledBackground: '#EAE6DD',
  disabledText: '#9EACA4',
};

export const tahajjudNoorColors: ThemeColors = {
  primary: '#06B6D4',
  primaryLight: '#102A36',
  primaryDark: '#0891B2',
  primaryPressed: '#0E7490',
  background: '#090D16',
  surface: 'rgba(18, 25, 39, 0.75)',
  surfaceSecondary: 'rgba(24, 34, 53, 0.65)',
  surfaceElevated: 'rgba(31, 44, 68, 0.85)',
  textPrimary: '#F8FAFC',
  textSecondary: '#94A3B8',
  textTertiary: '#64748B',
  textMuted: '#475569',
  textOnPrimary: '#090D16',
  success: '#10B981',
  warning: '#F59E0B',
  danger: '#F43F5E',
  error: '#F43F5E',
  dangerPressed: '#E11D48',
  dangerSurface: '#331520',
  info: '#38BDF8',
  completed: '#10B981',
  prayerFajr: '#1A2035',
  prayerDhuhr: '#222430',
  prayerAsr: '#24222E',
  prayerMaghrib: '#2A1C28',
  prayerIsha: '#141C30',
  border: '#223048',
  divider: '#1A2538',
  shadowColor: 'rgba(0, 0, 0, 0.5)',
  shadowElevated: 'rgba(0, 0, 0, 0.7)',
  overlay: 'rgba(5, 8, 14, 0.8)',
  tabInactive: '#64748B',
  tabActive: '#06B6D4',
  checkboxUnchecked: '#334155',
  checkboxChecked: '#06B6D4',
  disabledBackground: '#1A2436',
  disabledText: '#475569',
};

export const andalusianOasisColors: ThemeColors = {
  primary: '#1D4ED8',
  primaryLight: '#EBF2FF',
  primaryDark: '#1E40AF',
  primaryPressed: '#1E40AF',
  background: '#FDF6EE',
  surface: 'rgba(255, 255, 255, 0.88)',
  surfaceSecondary: 'rgba(245, 236, 225, 0.80)',
  surfaceElevated: 'rgba(255, 255, 255, 0.96)',
  textPrimary: '#382414',
  textSecondary: '#785B43',
  textTertiary: '#8C6C52',
  textMuted: '#A89078',
  textOnPrimary: '#FFFFFF',
  success: '#15803D',
  warning: '#D97706',
  danger: '#B91C1C',
  error: '#B91C1C',
  dangerPressed: '#991B1B',
  dangerSurface: '#FEE2E2',
  info: '#1D4ED8',
  completed: '#15803D',
  prayerFajr: '#EDE8F5',
  prayerDhuhr: '#FFF3E0',
  prayerAsr: '#FFEBD4',
  prayerMaghrib: '#FCE4E4',
  prayerIsha: '#E4EBF7',
  border: '#EADCCE',
  divider: '#F3E8DC',
  shadowColor: 'rgba(56, 36, 20, 0.08)',
  shadowElevated: 'rgba(56, 36, 20, 0.16)',
  overlay: 'rgba(30, 20, 10, 0.45)',
  tabInactive: '#8C6C52',
  tabActive: '#1D4ED8',
  checkboxUnchecked: '#DACCC0',
  checkboxChecked: '#1D4ED8',
  disabledBackground: '#EFE6DC',
  disabledText: '#A89078',
};

export const sacredTawafColors: ThemeColors = {
  primary: '#EAB308',
  primaryLight: '#332A17',
  primaryDark: '#CA8A04',
  primaryPressed: '#A16207',
  background: '#1E1B26',
  surface: 'rgba(41, 37, 52, 0.78)',
  surfaceSecondary: 'rgba(50, 45, 63, 0.68)',
  surfaceElevated: 'rgba(61, 55, 77, 0.88)',
  textPrimary: '#FFFFFF',
  textSecondary: '#C4B5D4',
  textTertiary: '#A093B2',
  textMuted: '#756A85',
  textOnPrimary: '#1E1B26',
  success: '#22C55E',
  warning: '#EAB308',
  danger: '#EF4444',
  error: '#EF4444',
  dangerPressed: '#DC2626',
  dangerSurface: '#3C1B24',
  info: '#60A5FA',
  completed: '#22C55E',
  prayerFajr: '#2F2942',
  prayerDhuhr: '#363038',
  prayerAsr: '#3B3138',
  prayerMaghrib: '#3D2735',
  prayerIsha: '#252538',
  border: '#3F3950',
  divider: '#342E43',
  shadowColor: 'rgba(0, 0, 0, 0.45)',
  shadowElevated: 'rgba(0, 0, 0, 0.65)',
  overlay: 'rgba(15, 12, 20, 0.8)',
  tabInactive: '#A093B2',
  tabActive: '#EAB308',
  checkboxUnchecked: '#4F4764',
  checkboxChecked: '#EAB308',
  disabledBackground: '#302A3C',
  disabledText: '#756A85',
};

export const blessedOliveColors: ThemeColors = {
  primary: '#4D7C0F',
  primaryLight: '#ECF5E6',
  primaryDark: '#3F6212',
  primaryPressed: '#3F6212',
  background: '#F2F6F1',
  surface: 'rgba(255, 255, 255, 0.88)',
  surfaceSecondary: 'rgba(232, 239, 230, 0.80)',
  surfaceElevated: 'rgba(255, 255, 255, 0.96)',
  textPrimary: '#1B2E1B',
  textSecondary: '#5C6E5C',
  textTertiary: '#708270',
  textMuted: '#8E9F8E',
  textOnPrimary: '#FFFFFF',
  success: '#4D7C0F',
  warning: '#B45309',
  danger: '#B91C1C',
  error: '#B91C1C',
  dangerPressed: '#991B1B',
  dangerSurface: '#FEE2E2',
  info: '#0D9488',
  completed: '#4D7C0F',
  prayerFajr: '#EBE8F2',
  prayerDhuhr: '#F5F3E4',
  prayerAsr: '#F6ECE0',
  prayerMaghrib: '#F8E4E5',
  prayerIsha: '#E4EAF0',
  border: '#DCE4DA',
  divider: '#E5EDE3',
  shadowColor: 'rgba(27, 46, 27, 0.07)',
  shadowElevated: 'rgba(27, 46, 27, 0.14)',
  overlay: 'rgba(15, 25, 15, 0.45)',
  tabInactive: '#708270',
  tabActive: '#4D7C0F',
  checkboxUnchecked: '#C6D1C4',
  checkboxChecked: '#4D7C0F',
  disabledBackground: '#E2E9E0',
  disabledText: '#8E9F8E',
};

export const samarkandTurquoiseColors: ThemeColors = {
  primary: '#0891B2',
  primaryLight: '#E6F7FA',
  primaryDark: '#0E7490',
  primaryPressed: '#0E7490',
  background: '#EDF9FA',
  surface: 'rgba(255, 255, 255, 0.88)',
  surfaceSecondary: 'rgba(224, 243, 245, 0.80)',
  surfaceElevated: 'rgba(255, 255, 255, 0.96)',
  textPrimary: '#0E2C3D',
  textSecondary: '#457085',
  textTertiary: '#5C879C',
  textMuted: '#80A2B3',
  textOnPrimary: '#FFFFFF',
  success: '#0D9488',
  warning: '#D97706',
  danger: '#C026D3',
  error: '#E11D48',
  dangerPressed: '#BE123C',
  dangerSurface: '#FFE4E6',
  info: '#0891B2',
  completed: '#0D9488',
  prayerFajr: '#E8E8F5',
  prayerDhuhr: '#FFF4E0',
  prayerAsr: '#F8EBE0',
  prayerMaghrib: '#FCE2EB',
  prayerIsha: '#E0EEF5',
  border: '#D1EAEF',
  divider: '#DCF0F4',
  shadowColor: 'rgba(14, 44, 61, 0.08)',
  shadowElevated: 'rgba(14, 44, 61, 0.15)',
  overlay: 'rgba(8, 30, 42, 0.45)',
  tabInactive: '#5C879C',
  tabActive: '#0891B2',
  checkboxUnchecked: '#B8D9DF',
  checkboxChecked: '#0891B2',
  disabledBackground: '#D8EDF1',
  disabledText: '#80A2B3',
};

export const celestialCaravanColors: ThemeColors = {
  primary: '#F97316',
  primaryLight: '#362114',
  primaryDark: '#EA580C',
  primaryPressed: '#C2410C',
  background: '#141026',
  surface: 'rgba(32, 27, 56, 0.78)',
  surfaceSecondary: 'rgba(43, 36, 74, 0.68)',
  surfaceElevated: 'rgba(53, 44, 90, 0.88)',
  textPrimary: '#FBFBFD',
  textSecondary: '#9D8EB5',
  textTertiary: '#7E6F95',
  textMuted: '#5C4E72',
  textOnPrimary: '#141026',
  success: '#22C55E',
  warning: '#F59E0B',
  danger: '#EF4444',
  error: '#EF4444',
  dangerPressed: '#DC2626',
  dangerSurface: '#3A1926',
  info: '#38BDF8',
  completed: '#22C55E',
  prayerFajr: '#282048',
  prayerDhuhr: '#32263F',
  prayerAsr: '#392842',
  prayerMaghrib: '#3F1E38',
  prayerIsha: '#1D1838',
  border: '#372E5C',
  divider: '#2D254C',
  shadowColor: 'rgba(0, 0, 0, 0.45)',
  shadowElevated: 'rgba(0, 0, 0, 0.65)',
  overlay: 'rgba(10, 8, 20, 0.8)',
  tabInactive: '#7E6F95',
  tabActive: '#F97316',
  checkboxUnchecked: '#4C3F6D',
  checkboxChecked: '#F97316',
  disabledBackground: '#2B2346',
  disabledText: '#5C4E72',
};

export const maghribLanternColors: ThemeColors = {
  primary: '#FB7185',
  primaryLight: '#3B1A28',
  primaryDark: '#E11D48',
  primaryPressed: '#BE123C',
  background: '#2A0B2E',
  surface: 'rgba(58, 22, 64, 0.78)',
  surfaceSecondary: 'rgba(72, 29, 79, 0.68)',
  surfaceElevated: 'rgba(87, 36, 95, 0.88)',
  textPrimary: '#FFFFFF',
  textSecondary: '#FDA4AF',
  textTertiary: '#DB8693',
  textMuted: '#A65E6B',
  textOnPrimary: '#2A0B2E',
  success: '#34D399',
  warning: '#FBBF24',
  danger: '#F87171',
  error: '#F87171',
  dangerPressed: '#EF4444',
  dangerSurface: '#441324',
  info: '#67E8F9',
  completed: '#34D399',
  prayerFajr: '#3B1C45',
  prayerDhuhr: '#42203D',
  prayerAsr: '#48223B',
  prayerMaghrib: '#4E1A38',
  prayerIsha: '#321440',
  border: '#55235E',
  divider: '#441A4C',
  shadowColor: 'rgba(0, 0, 0, 0.45)',
  shadowElevated: 'rgba(0, 0, 0, 0.65)',
  overlay: 'rgba(20, 5, 24, 0.8)',
  tabInactive: '#DB8693',
  tabActive: '#FB7185',
  checkboxUnchecked: '#672B70',
  checkboxChecked: '#FB7185',
  disabledBackground: '#3E1844',
  disabledText: '#A65E6B',
};

export const alAqsaSunsetColors: ThemeColors = {
  primary: '#D97706',
  primaryLight: '#FAF3E8',
  primaryDark: '#B45309',
  primaryPressed: '#92400E',
  background: '#EAE6F0',
  surface: 'rgba(255, 255, 255, 0.88)',
  surfaceSecondary: 'rgba(223, 218, 232, 0.80)',
  surfaceElevated: 'rgba(255, 255, 255, 0.96)',
  textPrimary: '#292524',
  textSecondary: '#57534E',
  textTertiary: '#736D66',
  textMuted: '#948E87',
  textOnPrimary: '#FFFFFF',
  success: '#16A34A',
  warning: '#D97706',
  danger: '#DC2626',
  error: '#DC2626',
  dangerPressed: '#B91C1C',
  dangerSurface: '#FEE2E2',
  info: '#0284C7',
  completed: '#16A34A',
  prayerFajr: '#E2DFED',
  prayerDhuhr: '#EDE5D8',
  prayerAsr: '#EFE0D4',
  prayerMaghrib: '#EED9DC',
  prayerIsha: '#D8D7E8',
  border: '#D1CBDC',
  divider: '#DCD7E6',
  shadowColor: 'rgba(41, 37, 36, 0.08)',
  shadowElevated: 'rgba(41, 37, 36, 0.16)',
  overlay: 'rgba(25, 20, 30, 0.45)',
  tabInactive: '#736D66',
  tabActive: '#D97706',
  checkboxUnchecked: '#BDB5C9',
  checkboxChecked: '#D97706',
  disabledBackground: '#D5CFDE',
  disabledText: '#948E87',
};

export const ISLAMIC_THEMES: IslamicThemeDefinition[] = [
  {
    id: 'fajr_awakening',
    name: 'Fajr Awakening',
    arabicName: 'فجر السكينة',
    tagline: 'By the dawn, and by the ten nights... (Surah Al-Fajr)',
    isDark: true,
    wallpaperAsset: require('../../assets/themes/fajr_awakening.jpg'),
    previewColors: {
      primary: '#F59E0B',
      background: '#161A36',
      surface: '#1E244B',
      accent: '#FCD5B5',
    },
    colors: fajrAwakeningColors,
  },
  {
    id: 'rawdah_emerald',
    name: 'Rawdah Emerald',
    arabicName: 'الروضة الشريفة',
    tagline: 'Between my house and my pulpit is a garden from Paradise.',
    isDark: false,
    wallpaperAsset: require('../../assets/themes/rawdah_emerald.jpg'),
    previewColors: {
      primary: '#0F8A52',
      background: '#F9F7F2',
      surface: '#EBF5EF',
      accent: '#D4A017',
    },
    colors: rawdahEmeraldColors,
  },
  {
    id: 'tahajjud_noor',
    name: 'Tahajjud Noor',
    arabicName: 'نور الليل',
    tagline: 'And during a part of the night, keep vigil therein... (Surah Al-Isra)',
    isDark: true,
    wallpaperAsset: require('../../assets/themes/tahajjud_noor.jpg'),
    previewColors: {
      primary: '#06B6D4',
      background: '#090D16',
      surface: '#121927',
      accent: '#38BDF8',
    },
    colors: tahajjudNoorColors,
  },
  {
    id: 'andalusian_oasis',
    name: 'Andalusian Oasis',
    arabicName: 'رياض الأندلس',
    tagline: 'Water courtyards, horseshoe arches, and jasmine gardens.',
    isDark: false,
    wallpaperAsset: require('../../assets/themes/andalusian_oasis.jpg'),
    previewColors: {
      primary: '#1D4ED8',
      background: '#FDF6EE',
      surface: '#F5ECE1',
      accent: '#D97706',
    },
    colors: andalusianOasisColors,
  },
  {
    id: 'sacred_tawaf',
    name: 'Sacred Tawaf',
    arabicName: 'مكة المكرمة',
    tagline: 'Concentric rings of devotion around the Holy Kaaba.',
    isDark: true,
    wallpaperAsset: require('../../assets/themes/sacred_tawaf.jpg'),
    previewColors: {
      primary: '#EAB308',
      background: '#1E1B26',
      surface: '#292534',
      accent: '#CA8A04',
    },
    colors: sacredTawafColors,
  },
  {
    id: 'blessed_olive',
    name: 'Blessed Olive Grove',
    arabicName: 'زيتون القدس',
    tagline: 'Lit from a blessed tree, an olive... (Surah An-Nur)',
    isDark: false,
    wallpaperAsset: require('../../assets/themes/blessed_olive.jpg'),
    previewColors: {
      primary: '#4D7C0F',
      background: '#F2F6F1',
      surface: '#E8EFE6',
      accent: '#B45309',
    },
    colors: blessedOliveColors,
  },
  {
    id: 'samarkand_turquoise',
    name: 'Samarkand Turquoise',
    arabicName: 'سيراميك سمرقند',
    tagline: 'Fluted turquoise domes and glazed Silk Road mosaics.',
    isDark: false,
    wallpaperAsset: require('../../assets/themes/samarkand_turquoise.jpg'),
    previewColors: {
      primary: '#0891B2',
      background: '#EDF9FA',
      surface: '#E0F3F5',
      accent: '#0D9488',
    },
    colors: samarkandTurquoiseColors,
  },
  {
    id: 'celestial_caravan',
    name: 'Celestial Caravan',
    arabicName: 'قافلة النجوم',
    tagline: 'And landmarks; and by the stars they guide themselves. (Surah An-Nahl)',
    isDark: true,
    wallpaperAsset: require('../../assets/themes/celestial_caravan.jpg'),
    previewColors: {
      primary: '#F97316',
      background: '#141026',
      surface: '#201B38',
      accent: '#FBBF24',
    },
    colors: celestialCaravanColors,
  },
  {
    id: 'maghrib_lantern',
    name: 'Maghrib Lantern',
    arabicName: 'غروب الإفطار',
    tagline: 'Warm sunset fellowship, breaking fast, and glowing lanterns.',
    isDark: true,
    wallpaperAsset: require('../../assets/themes/maghrib_lantern.jpg'),
    previewColors: {
      primary: '#FB7185',
      background: '#2A0B2E',
      surface: '#3A1640',
      accent: '#FBBF24',
    },
    colors: maghribLanternColors,
  },
  {
    id: 'al_aqsa_sunset',
    name: 'Al-Aqsa Sunset',
    arabicName: 'قدس السلام',
    tagline: 'The golden dome gleaming under the lavender dusk of Jerusalem.',
    isDark: false,
    wallpaperAsset: require('../../assets/themes/al_aqsa_sunset.jpg'),
    previewColors: {
      primary: '#D97706',
      background: '#EAE6F0',
      surface: '#DFDAE8',
      accent: '#B45309',
    },
    colors: alAqsaSunsetColors,
  },
];

export function createGalleryThemeColors(primary: string, background: string, isDark: boolean): ThemeColors {
  if (isDark) {
    return {
      primary,
      primaryLight: '#2A2C38',
      primaryDark: primary,
      primaryPressed: primary,
      background,
      surface: 'rgba(25, 27, 38, 0.85)',
      surfaceSecondary: 'rgba(35, 38, 52, 0.75)',
      surfaceElevated: 'rgba(45, 49, 66, 0.9)',
      textPrimary: '#F8FAFC',
      textSecondary: '#94A3B8',
      textTertiary: '#64748B',
      textMuted: '#475569',
      textOnPrimary: '#090D16',
      success: '#10B981',
      warning: '#F59E0B',
      danger: '#EF4444',
      error: '#EF4444',
      dangerPressed: '#DC2626',
      dangerSurface: '#381E28',
      info: '#38BDF8',
      completed: '#10B981',
      prayerFajr: '#2B2B5C',
      prayerDhuhr: '#2E2848',
      prayerAsr: '#342540',
      prayerMaghrib: '#381F38',
      prayerIsha: '#1E2248',
      border: '#2C3464',
      divider: '#222952',
      shadowColor: 'rgba(0, 0, 0, 0.5)',
      shadowElevated: 'rgba(0, 0, 0, 0.7)',
      overlay: 'rgba(10, 12, 28, 0.75)',
      tabInactive: '#857F9A',
      tabActive: primary,
      checkboxUnchecked: '#434D7E',
      checkboxChecked: primary,
      disabledBackground: '#262E58',
      disabledText: '#65607A',
    };
  }
  return {
    primary,
    primaryLight: '#EDF5FE',
    primaryDark: primary,
    primaryPressed: primary,
    background,
    surface: '#FFFFFF',
    surfaceSecondary: 'rgba(245, 247, 250, 0.85)',
    surfaceElevated: '#FFFFFF',
    textPrimary: '#1E293B',
    textSecondary: '#64748B',
    textTertiary: '#94A3B8',
    textMuted: '#CBD5E1',
    textOnPrimary: '#FFFFFF',
    success: '#10B981',
    warning: '#F59E0B',
    danger: '#EF4444',
    error: '#EF4444',
    dangerPressed: '#DC2626',
    dangerSurface: '#FEE2E2',
    info: primary,
    completed: '#10B981',
    prayerFajr: '#EDEBF5',
    prayerDhuhr: '#FFF6E5',
    prayerAsr: '#FFF0DB',
    prayerMaghrib: '#FFE6E6',
    prayerIsha: '#E8ECF5',
    border: '#E2E8F0',
    divider: '#F1F5F9',
    shadowColor: 'rgba(0, 0, 0, 0.08)',
    shadowElevated: 'rgba(0, 0, 0, 0.15)',
    overlay: 'rgba(0, 0, 0, 0.45)',
    tabInactive: '#64748B',
    tabActive: primary,
    checkboxUnchecked: '#CBD5E1',
    checkboxChecked: primary,
    disabledBackground: '#F1F5F9',
    disabledText: '#94A3B8',
  };
}

export const GALLERY_THEME_DEFINITIONS: IslamicThemeDefinition[] = [
  // Pure colors
  {
    id: 'color_sky_blue',
    name: 'Sky Blue',
    arabicName: 'سماء زرقاء',
    tagline: 'Fresh and clear like the morning sky.',
    isDark: false,
    previewColors: { primary: '#7AA7FF', background: '#E1F3FE', surface: '#FFFFFF', accent: '#7AA7FF' },
    colors: createGalleryThemeColors('#7AA7FF', '#E1F3FE', false),
  },
  {
    id: 'color_coral_pink',
    name: 'Coral Pink',
    arabicName: 'وردي مرجاني',
    tagline: 'Gentle warmth and gentle serenity.',
    isDark: false,
    previewColors: { primary: '#F47C96', background: '#FDF2F5', surface: '#FFFFFF', accent: '#F47C96' },
    colors: createGalleryThemeColors('#F47C96', '#FDF2F5', false),
  },
  {
    id: 'color_jade_teal',
    name: 'Jade Teal',
    arabicName: 'فيروزي هادئ',
    tagline: 'Refreshing balance of calm and focus.',
    isDark: false,
    previewColors: { primary: '#47B5A4', background: '#EEF8F6', surface: '#FFFFFF', accent: '#47B5A4' },
    colors: createGalleryThemeColors('#47B5A4', '#EEF8F6', false),
  },
  {
    id: 'color_dark_slate',
    name: 'Dark Slate',
    arabicName: 'رمادي ليلي',
    tagline: 'Deep contrast for nighttime contemplation.',
    isDark: true,
    previewColors: { primary: '#8A99AD', background: '#1A1B22', surface: '#252834', accent: '#8A99AD' },
    colors: createGalleryThemeColors('#8A99AD', '#1A1B22', true),
  },
  {
    id: 'color_terracotta',
    name: 'Terracotta',
    arabicName: 'أحمر قرميدي',
    tagline: 'Rich earth tones and timeless craft.',
    isDark: false,
    previewColors: { primary: '#DE625E', background: '#FDF3F2', surface: '#FFFFFF', accent: '#DE625E' },
    colors: createGalleryThemeColors('#DE625E', '#FDF3F2', false),
  },
  {
    id: 'color_marigold',
    name: 'Marigold',
    arabicName: 'أصفر مشرق',
    tagline: 'Uplifting dawn radiance and positivity.',
    isDark: false,
    previewColors: { primary: '#FFC539', background: '#FFFBF0', surface: '#FFFFFF', accent: '#E5A81A' },
    colors: createGalleryThemeColors('#FFC539', '#FFFBF0', false),
  },
  {
    id: 'color_emerald',
    name: 'Emerald',
    arabicName: 'أخضر زمردي',
    tagline: 'Lush greenery and vitality.',
    isDark: false,
    previewColors: { primary: '#1EA273', background: '#EEF9F4', surface: '#FFFFFF', accent: '#1EA273' },
    colors: createGalleryThemeColors('#1EA273', '#EEF9F4', false),
  },
  {
    id: 'color_tangerine',
    name: 'Tangerine',
    arabicName: 'برتقالي دافئ',
    tagline: 'Warm energy and motivation.',
    isDark: false,
    previewColors: { primary: '#F4864B', background: '#FDF5F0', surface: '#FFFFFF', accent: '#F4864B' },
    colors: createGalleryThemeColors('#F4864B', '#FDF5F0', false),
  },
  {
    id: 'color_royal_purple',
    name: 'Royal Purple',
    arabicName: 'بنفسجي ملكي',
    tagline: 'Dignified serenity and evening calm.',
    isDark: false,
    previewColors: { primary: '#8F4BE8', background: '#F7F2FD', surface: '#FFFFFF', accent: '#8F4BE8' },
    colors: createGalleryThemeColors('#8F4BE8', '#F7F2FD', false),
  },
  // Textures
  {
    id: 'texture_rice_paper',
    name: 'Rice Paper',
    arabicName: 'ورق الأرز',
    tagline: 'Tactile craft paper with blue accents.',
    isDark: false,
    wallpaperAsset: require('../../assets/themes/gallery/texture_paper_bg.png'),
    previewColors: { primary: '#5B9DFF', background: '#F8F9FA', surface: '#FFFFFF', accent: '#5B9DFF' },
    colors: createGalleryThemeColors('#5B9DFF', '#F8F9FA', false),
  },
  {
    id: 'texture_kraft',
    name: 'Warm Parchment',
    arabicName: 'ورق قديم',
    tagline: 'Warm parchment texture with crimson details.',
    isDark: false,
    wallpaperAsset: require('../../assets/themes/gallery/texture_paper_bg.png'),
    previewColors: { primary: '#E05F5A', background: '#F6F3EE', surface: '#FFFFFF', accent: '#E05F5A' },
    colors: createGalleryThemeColors('#E05F5A', '#F6F3EE', false),
  },
  {
    id: 'texture_lavender',
    name: 'Lavender Sheet',
    arabicName: 'ورق الخزامى',
    tagline: 'Pastel lavender fiber texture.',
    isDark: false,
    wallpaperAsset: require('../../assets/themes/gallery/texture_paper_bg.png'),
    previewColors: { primary: '#8E4AE8', background: '#F5F2F9', surface: '#FFFFFF', accent: '#8E4AE8' },
    colors: createGalleryThemeColors('#8E4AE8', '#F5F2F9', false),
  },
  {
    id: 'texture_sage',
    name: 'Sage Linen',
    arabicName: 'كتان حكيم',
    tagline: 'Gentle organic sage weave.',
    isDark: false,
    wallpaperAsset: require('../../assets/themes/gallery/texture_paper_bg.png'),
    previewColors: { primary: '#1EA273', background: '#F2F6F3', surface: '#FFFFFF', accent: '#1EA273' },
    colors: createGalleryThemeColors('#1EA273', '#F2F6F3', false),
  },
  // Scenery
  {
    id: 'scenery_lighthouse',
    name: 'Lighthouse Haven',
    arabicName: 'المنارة البحرية',
    tagline: 'Guiding light beside tranquil azure waves.',
    isDark: false,
    wallpaperAsset: require('../../assets/themes/gallery/Theme10.jpeg'),
    previewColors: { primary: '#0284C7', background: '#D9F2FC', surface: '#FFFFFF', accent: '#0284C7' },
    colors: createGalleryThemeColors('#0284C7', '#D9F2FC', false),
  },
  {
    id: 'scenery_family',
    name: 'Sunny Picnic',
    arabicName: 'نزهة عائلية',
    tagline: 'Joyful park stroll under the open sky.',
    isDark: false,
    wallpaperAsset: require('../../assets/themes/gallery/Theme9.jpeg'),
    previewColors: { primary: '#06B6D4', background: '#E2F8FA', surface: '#FFFFFF', accent: '#06B6D4' },
    colors: createGalleryThemeColors('#06B6D4', '#E2F8FA', false),
  },
  {
    id: 'scenery_night_road',
    name: 'Night Journey',
    arabicName: 'رحلة الليل',
    tagline: 'Winding mountain path beneath shooting stars.',
    isDark: true,
    wallpaperAsset: require('../../assets/themes/gallery/Theme8.jpeg'),
    previewColors: { primary: '#38BDF8', background: '#16192E', surface: '#202442', accent: '#38BDF8' },
    colors: createGalleryThemeColors('#38BDF8', '#16192E', true),
  },
  {
    id: 'scenery_cherry_blossom',
    name: 'Sakura River',
    arabicName: 'أزهار الكرز',
    tagline: 'Blossoms fluttering across a peaceful stream.',
    isDark: false,
    wallpaperAsset: require('../../assets/themes/gallery/Theme7.jpeg'),
    previewColors: { primary: '#F43F5E', background: '#FDF2F4', surface: '#FFFFFF', accent: '#F43F5E' },
    colors: createGalleryThemeColors('#F43F5E', '#FDF2F4', false),
  },
  {
    id: 'scenery_green_hill',
    name: 'Green Meadow',
    arabicName: 'المرج الأخضر',
    tagline: 'Rolling green pastures and gentle breezes.',
    isDark: false,
    wallpaperAsset: require('../../assets/themes/gallery/Theme6.jpeg'),
    previewColors: { primary: '#10B981', background: '#F0F9F4', surface: '#FFFFFF', accent: '#10B981' },
    colors: createGalleryThemeColors('#10B981', '#F0F9F4', false),
  },
  {
    id: 'scenery_cyclist',
    name: 'Breeze Ride',
    arabicName: 'نسيم الحقول',
    tagline: 'Cycling through wildflower hills under summer skies.',
    isDark: false,
    wallpaperAsset: require('../../assets/themes/gallery/Theme5.jpeg'),
    previewColors: { primary: '#0EA5E9', background: '#E0F5FE', surface: '#FFFFFF', accent: '#0EA5E9' },
    colors: createGalleryThemeColors('#0EA5E9', '#E0F5FE', false),
  },
  {
    id: 'scenery_eiffel',
    name: 'Parisian Twilight',
    arabicName: 'أضواء باريس',
    tagline: 'Golden lights gleaming along the Seine river.',
    isDark: true,
    wallpaperAsset: require('../../assets/themes/gallery/Theme4.jpeg'),
    previewColors: { primary: '#818CF8', background: '#171B33', surface: '#22284C', accent: '#818CF8' },
    colors: createGalleryThemeColors('#818CF8', '#171B33', true),
  },
  {
    id: 'scenery_mountain_camp',
    name: 'Twilight Campfire',
    arabicName: 'مخيم الشفق',
    tagline: 'Peaceful campfire glow in the purple twilight.',
    isDark: true,
    wallpaperAsset: require('../../assets/themes/gallery/Theme3.jpeg'),
    previewColors: { primary: '#A78BFA', background: '#1F1B36', surface: '#2A244A', accent: '#A78BFA' },
    colors: createGalleryThemeColors('#A78BFA', '#1F1B36', true),
  },
  {
    id: 'scenery_teddy',
    name: 'Warm Teddy',
    arabicName: 'الدب الوديع',
    tagline: 'Cozy scarf and sweet comfort.',
    isDark: false,
    wallpaperAsset: require('../../assets/themes/gallery/Theme1.jpeg'),
    previewColors: { primary: '#F472B6', background: '#FDF2F6', surface: '#FFFFFF', accent: '#F472B6' },
    colors: createGalleryThemeColors('#F472B6', '#FDF2F6', false),
  },
  {
    id: 'scenery_astronaut',
    name: 'Cosmic Journey',
    arabicName: 'رحلة الفضاء',
    tagline: 'Reaching for the stars beyond the horizon.',
    isDark: true,
    wallpaperAsset: require('../../assets/themes/gallery/Theme2.jpeg'),
    previewColors: { primary: '#A3E635', background: '#121217', surface: '#1E1E26', accent: '#A3E635' },
    colors: createGalleryThemeColors('#A3E635', '#121217', true),
  },
  {
    id: 'scenery_sunflowers',
    name: 'Sunflower Bloom',
    arabicName: 'زهرة الشمس',
    tagline: 'Sunflowers turning their faces toward the light.',
    isDark: false,
    previewColors: { primary: '#EAB308', background: '#FDFBF0', surface: '#FFFFFF', accent: '#EAB308' },
    colors: createGalleryThemeColors('#EAB308', '#FDFBF0', false),
  },
  {
    id: 'scenery_clouds',
    name: 'Skyward Dreams',
    arabicName: 'سحب الأمل',
    tagline: 'Paper airplane drifting high among white clouds.',
    isDark: false,
    previewColors: { primary: '#38BDF8', background: '#E2F3FD', surface: '#FFFFFF', accent: '#38BDF8' },
    colors: createGalleryThemeColors('#38BDF8', '#E2F3FD', false),
  },
];

export const ISLAMIC_THEMES_MAP: Record<string, IslamicThemeDefinition> = [
  ...ISLAMIC_THEMES,
  ...GALLERY_THEME_DEFINITIONS,
].reduce((acc, theme) => {
  acc[theme.id] = theme;
  return acc;
}, {} as Record<string, IslamicThemeDefinition>);

